[feature] Added user info to status page #104
openwisp/openwisp-wifi-login-pages pull request #139
Opened 2020-12-07 20:17 UTC by NoumbissiValere

Closes #104

2020-12-07 20:39 UTC, NoumbissiValere commented
@nemesisdesign the complain is not part of this solution but I don't get it why linting is complaining in [phone-token-controller](https://github.com/openwisp/openwisp-wifi-login-pages/blob/master/server/controllers/mobile-phone-token-controller.js#L23) and not in [phone change number](https://github.com/openwisp/openwisp-wifi-login-pages/blob/master/server/controllers/mobile-phone-number-change-controller.js#L24) for the same thing.

2020-12-08 03:15 UTC, NoumbissiValere commented
[PR 202](https://github.com/openwisp/openwisp-radius/pull/202) is needed to test this work

2020-12-09 03:26 UTC, nemesisdesign requested changes
Good progress @NoumbissiValere, here's a quick review, will need to look more in depth into it tomorrow and test it as well.

2020-12-09 03:26 UTC, nemesisdesign commented on client/components/status/status.js
> +        const user_info = {};
use camel case in javascript code please

2020-12-09 03:26 UTC, nemesisdesign commented on client/components/status/status.js
> +                      );
Please define the fields one by one and get the translatable text in a way that is consistent with the rest of the application (create one config key for each word).

2020-12-10 02:51 UTC, nemesisdesign requested changes
- The status row indicated in the wireframe is missing.
- I would switch from using a table to using a series of `<p>` elements, `<label>` and span, eg:
`<p><label>Email:</label><span>email value</span></p>`
- I also suggest using the CSS of the component to style the label to be bold and to have some margin on the right side.
- Please when you need to add space between elements use CSS, not <br> elements, the space below is huge and looks bad:

![Screenshot from 2020-12-09 21-41-20](https://user-images.githubusercontent.com/841044/101714869-67f43700-3a68-11eb-9c92-b9f45bdf43a8.png)

2020-12-11 00:01 UTC, NoumbissiValere commented
@nemesisdesign should I remove this text:
```WiFi Login Successful!

You can now use the internet.

You may leave this page open in case you want to log out.
```

2020-12-11 04:07 UTC, nemesisdesign commented
@NoumbissiValere leave it for now, I will think about it a bit more.

2020-12-13 22:47 UTC, nemesisdesign requested changes
Tested and looks good, please address the following concerns below so we can merge.

2020-12-13 22:47 UTC, nemesisdesign commented on .eslintrc.json
> +    "jsx-a11y/label-has-associated-control": 0,
adding this rule here affects the whole project. It should be possible to add an ignore rule only in the interested file, which is a lot better.

2020-12-13 22:47 UTC, nemesisdesign commented on client/components/status/status.js
> +                })}
why did you increase the indentation here? It looks like an unnecessary change and I think it should be reverted.

2020-12-13 22:47 UTC, nemesisdesign commented on internals/generators/organization/config.yml.hbs
> +      {{/if}}
let's not use the if here, the reason is that if mobile phone verification is enabled at a later step, the user will have to modify manually the config file which is time consuming and error prone.

2020-12-13 22:47 UTC, nemesisdesign commented on org-configurations/default-configuration.yml
> +            en: "Username"
please add the mobile phone field here as well for consistency with the change requested above

2020-12-16 01:49 UTC, nemesisdesign approved these changes

2020-12-16 01:49 UTC, merged