[feature] Added phone number to register and login #144
openwisp/openwisp-wifi-login-pages pull request #145
Opened 2020-12-28 21:08 UTC by NoumbissiValere

Closes #144

2020-12-29 18:19 UTC, NoumbissiValere commented
This PR needs [openwisp_radius #209](https://github.com/openwisp/openwisp-radius/pull/210) for testing

2020-12-31 02:05 UTC, nemesisdesign requested changes
Good progress, see below.

2020-12-31 02:05 UTC, nemesisdesign commented on client/components/login/login.js
> -                    type={input_fields.email.type}
please ensure the configuration mirrors and reuses the same configuration used for the registration component! Do as it's done in the `mobile-phone-change` component, if you inspect that component (check `index.js`) you'll see the configuration is taken from the registration component:

https://github.com/openwisp/openwisp-wifi-login-pages/blob/f4fee4b1ab52156d3026296120ba92c1d1c2f1d5/client/components/mobile-phone-change/index.js#L9-L11

Ensure also the HTML is exactly the same as in the change phone number and registration component.

2020-12-31 02:05 UTC, nemesisdesign commented on client/components/login/login.js
> +                )}
I think we could make a method here:
```javascript
{this.renderLoginField()}
```

```javascript
renderLoginField() {
    if (settings.mobile_phone_verification) {
        return this.renderPhoneField();
    }
    return this.renderEmailField();
}
```

See also https://reactjs.org/docs/conditional-rendering.html.

2020-12-31 02:05 UTC, nemesisdesign commented on internals/generators/organization/config.yml.hbs
> +            en: "mobile phone number"
if you follow the suggestions above, this should not be needed

2020-12-31 02:05 UTC, nemesisdesign commented on org-configurations/default-configuration.yml
> +            en: "mobile phone number"
if you follow the suggestions above, this should not be needed

2020-12-31 02:05 UTC, nemesisdesign commented on client/components/login/login.test.js
> +    expect(wrapper.state("phone_number")).not.toEqual("");
ensure there's 1 test for the email scenario and 1 for the phone number scenario please

2021-01-06 00:23 UTC, nemesisdesign requested changes

2021-01-06 00:23 UTC, nemesisdesign commented on client/test-config.json
> +]
final blank line missing here

2021-01-06 00:23 UTC, nemesisdesign commented on org-configurations/default-configuration.yml
> +          # only_countries: ["it", "de", "uk"]
remove the commented options please

2021-01-11 00:31 UTC, nemesisdesign approved these changes

2021-01-11 00:31 UTC, merged