[feature] Added server side logging
openwisp/openwisp-wifi-login-pages pull request #239
Opened 2021-05-20 11:27 UTC by codesankalp

Closes #82 

Tasks done:
1. Added Winston for logging
2. Integrated morgan with Winston to log HTTP requests
3. Removed checking for status code to handle timeout error and connection refused error.

2021-05-22 02:02 UTC, nemesisdesign requested changes
I think by default we should do:

- log level: `debug` if development, `warning` if production (as you did) but should be possible to override this in some way (env var? what's the best practice here?)
- output: console by default, but should be possible to configure it (following the same method that we'l chose for log level) to a different transport

Can we log HTTP requests by default during dev?

Please also add information to the README on how to override logging configuration.

2021-05-22 17:42 UTC, codesankalp commented on server/morganMiddleware.js
> +  return env !== "development";
Yes

2021-05-22 17:45 UTC, codesankalp commented on server/loggerConfig.js
> +  debug: process.env.DEBUG_LOG_FILE || "logs/debug.log",
There is a single file for all logs i.e. `logs/all.log` but I thought having separate log files for different types will be better.
This is configurable like if we want to change the log file path then we have to pass it in environment variables.
I will document these things in README.

2021-05-22 17:47 UTC, codesankalp commented on server/utils/logger.js
> +  return isDevelopment ? "debug" : "warn";
It depends on the process like development or builds. But I will add an environment variable to override this also.

2021-05-24 18:30 UTC, nemesisdesign commented on server/loggerConfig.js
> +  debug: process.env.DEBUG_LOG_FILE || "logs/debug.log",
Make sure that by default everything goes to one file.

2021-05-24 18:30 UTC, nemesisdesign commented on README.md
> +| **LOG_LEVEL**        | (optional) This can be used to set the level of logging. The available values are `warn` and `debug`. By default log level is set to `debug` during development and `warn` dur
> The available values are `warn` and `debug`.

What about `info` and `error`?

2021-05-24 18:41 UTC, nemesisdesign commented
Please open the PR from a branch of this repository.

2021-05-24 18:41 UTC, closed without merging