[feature] Allow specifying if link should be shown to verified users #107
openwisp/openwisp-wifi-login-pages pull request #269
Opened 2021-06-14 14:27 UTC by codesankalp

Passed userData in shouldLinkBeShown to handle links for verified users.

Closes #107

2021-06-19 22:38 UTC, nemesisdesign requested changes
Please rebase on the latest master.

2021-06-20 13:34 UTC, codesankalp commented
I have tested it for default and mobile verification.

2021-06-21 19:47 UTC, nemesisdesign requested changes
Almost.. found one issue.

2021-06-21 19:47 UTC, nemesisdesign commented on client/utils/should-link-be-shown.js
> +    return link.method === "mobile_phone";
This is not working according to my test.
And indeed it looks quite wrong doesn't it? Why do you test if the link method is "mobile_phone"?
I think it should be: `return link.method === userData.method;`, this fixes the behavior in my manual testing, but please change your tests to catch this mistake and let me know which test is the failing one once it's done, so I will double check it.

2021-06-22 15:24 UTC, codesankalp commented on client/utils/utils.test.js
> +  });
This is the failing test if we remove the changes made in commit https://github.com/openwisp/openwisp-wifi-login-pages/pull/269/commits/5d5161a3434aa620ece014144efdc9da4ded46b5

2021-06-23 00:44 UTC, nemesisdesign approved these changes

2021-06-23 00:45 UTC, merged