[feature] Added browser based tests using selenium #237
openwisp/openwisp-wifi-login-pages pull request #319
Opened 2021-07-27 09:21 UTC by codesankalp

Added password-change.test.js

Closes #237

2021-08-02 17:44 UTC, nemesisdesign reviewed
I think then just adding mobile verification flow (with one failed attempt on purpose and then 
 a successful attempt) and change mobile phone number will be enough :+1:.

2021-08-03 20:35 UTC, codesankalp commented
> I think then just adding mobile verification flow (with one failed attempt on purpose and then
> a successful attempt) and change mobile phone number will be enough.

I am working on it, but it will fail in CI because the mobile verification configuration of the new organization is needed before running `yarn start`.

2021-08-06 20:52 UTC, nemesisdesign reviewed
Looks good, it runs, I tried it also locally, I will need a bit more time to review the code to double check that all new tests are good.

Please see my comment below.

2021-08-06 20:52 UTC, nemesisdesign commented on README.md
>     must be present or alternatively
BTW I noticed an unfinished sentence here, can you please remove the unfinished part?

2021-08-18 00:59 UTC, nemesisdesign requested changes
Can you rebase on the latest master please?

2021-08-21 00:56 UTC, nemesisdesign reviewed
@codesankalp is there a chance you can an useful test for the language switcher?

2021-08-21 01:01 UTC, codesankalp commented
> @codesankalp is there a chance you can an useful test for the language switcher?

Can we change the default configuration file (to add Italiano as a language in the header)?

2021-08-21 01:01 UTC, nemesisdesign commented
> > @codesankalp is there a chance you can an useful test for the language switcher?
> 
> Can we change the default configuration file (to add Italiano as a language in the header)?

@codesankalp if we can we do it only in the browser tests for sure

2021-08-30 08:15 UTC, codesankalp commented on browser-test/password-confirm.test.js
> +  it("should show not found on password confirm", async () => {
It tests the failure of password-confirm when uid and token are invalid.

2021-08-30 14:06 UTC, codesankalp commented on browser-test/mobile-verfication.test.js
> +      "div > p:nth-child(5) > span",
I tried but this is the one that is working.

2021-08-30 18:40 UTC, nemesisdesign approved these changes

2021-08-30 18:41 UTC, merged