[feature] Added sticky message #347
openwisp/openwisp-wifi-login-pages pull request #356
Opened 2021-08-21 08:40 UTC by codesankalp

Added custom html support for sticky message

Closes #347

2021-08-22 19:01 UTC, nemesisdesign requested changes
Good progress @codesankalp, I also have a few doubts here.

2021-08-22 19:01 UTC, nemesisdesign commented on README.md
> +#### Header
I think this should be called "Sticky message" and should be listed after "Second logo" above.

2021-08-23 17:12 UTC, nemesisdesign approved these changes
I sent some improvemens in a1121d38b0dd151a1c733b083f5c3e4bcd30ce11, please double check and let me know. LGTM now :+1:.

2021-08-24 04:45 UTC, codesankalp reviewed
Yes it looks good

2021-08-24 16:53 UTC, merged