[docs] added ansible-role link
openwisp/openwisp-wifi-login-pages pull request #442
Opened 2021-10-02 06:47 UTC by atharmohammad

Closes #364

2021-10-02 16:04 UTC, codesankalp requested changes
@atharmohammad QA-Checks are failing, Can you please fix it?

2021-10-02 16:48 UTC, atharmohammad commented
> @atharmohammad QA-Checks are failing, Can you please fix it?

fixing it !

2021-10-05 00:58 UTC, nemesisdesign requested changes

2021-10-05 00:58 UTC, nemesisdesign commented on README.md
> +An automated installer is available at [ansible-openwisp-wifi-login-pages](https://github.com/openwisp/ansible-openwisp-wifi-login-pages/)
I would simplify: "An automated installer is available at" > "See", and add a full stop after the link.

2021-10-05 15:59 UTC, merged