[feature] Limit consecutive SMS sending #683
openwisp/openwisp-wifi-login-pages pull request #686
Opened 2023-07-26 11:32 UTC by pandafy

Closes #683

2023-07-26 11:36 UTC, pandafy commented on .github/workflows/ci.yml
> +          curl -L https://github.com/openwisp/openwisp-radius/tarball/issues/481-limit-sms-tokens -o openwisp-radius.tar.gz
TODO: Update this before merging.

2023-07-26 17:35 UTC, nemesifier requested changes

2023-07-26 17:35 UTC, nemesifier commented on .github/workflows/ci.yml
> +          pip install --force-reinstall --no-deps "https://github.com/openwisp/openwisp-utils/tarball/fallback-positiveintegerfield"
you can remove this

2023-07-26 17:35 UTC, nemesifier commented on client/components/mobile-phone-verification/mobile-phone-verification.js
> +          this.setState({resendButtonDisabledTimeout: response.data.timeout});
let's rename timeout as indicated in openwisp-radius, I think `cooldown` is easy to understand.

2023-07-31 19:01 UTC, nemesifier requested changes
Please make sure the button to resend the SMS is dimmed while disabled, eg: we can lower it's opacity to 0.3/0.4 (make sure the mouseover event doesn't trigger a change of color/opacity).

See also my comment below.

2023-08-01 22:49 UTC, nemesifier approved these changes

2023-08-01 22:50 UTC, merged